<Project>
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisLevel>latest-recommended</AnalysisLevel>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <Version>0.0.9-nightly.20260717</Version>
        <AssemblyVersion>0.0.9.0</AssemblyVersion>
        <FileVersion>0.0.9.0</FileVersion>
        <Authors>51193</Authors>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/51193/origo</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageProjectUrl>https://github.com/51193/origo</PackageProjectUrl>
    </PropertyGroup>
</Project>
