using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Origo.Core.SourceGeneration;

[Generator(LanguageNames.CSharp)]
public sealed class TypedDataGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Origo.Core.Snd.Metadata.SndInlineTypesAttribute";
    private const string TypedDataFullName = "Origo.Core.Snd.Metadata.TypedData";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var typeListProvider = context.CompilationProvider
            .Select((compilation, ct) => ExtractInlineTypes(compilation));

        context.RegisterSourceOutput(typeListProvider, GenerateTypedDataExtensions);
    }

    private static List<InlineTypeInfo> ExtractInlineTypes(Compilation compilation)
    {
        var result = new List<InlineTypeInfo>();

        foreach (var attributeData in compilation.Assembly.GetAttributes())
        {
            if (attributeData.AttributeClass?.ToDisplayString() != AttributeFullName)
                continue;

            foreach (var arg in attributeData.ConstructorArguments)
            {
                if (arg.Kind == TypedConstantKind.Array)
                {
                    foreach (var element in arg.Values)
                    {
                        if (element.Value is INamedTypeSymbol typeSymbol)
                            result.Add(CreateTypeInfo(typeSymbol));
                        else if (element.Value is ITypeSymbol ts)
                            result.Add(CreateTypeInfo(ts));
                    }
                }
                else if (arg.Value is INamedTypeSymbol singleType)
                {
                    result.Add(CreateTypeInfo(singleType));
                }
            }
        }

        return result;
    }

    private static InlineTypeInfo CreateTypeInfo(ITypeSymbol typeSymbol)
    {
        var kind = GenerateKindName(typeSymbol);
        var fullName = typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var clrName = typeSymbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat);
        var isReferenceType = typeSymbol.IsReferenceType;
        var specialType = typeSymbol.SpecialType;
        var fitsInline = IsInlineCandidate(typeSymbol);

        return new InlineTypeInfo
        {
            KindIndex = kind,
            FullTypeName = fullName,
            ClrTypeName = clrName,
            IsReferenceType = isReferenceType,
            SpecialType = specialType,
            FitsInline = fitsInline,
            TypeSymbol = typeSymbol
        };
    }

    private static bool IsInlineCandidate(ITypeSymbol type)
    {
        if (type.IsReferenceType) return false;
        var full = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return !full.Contains("global::System.Decimal");
    }

    private static string GenerateKindName(ITypeSymbol type)
    {
        var full = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return full switch
        {
            "global::System.Byte" => "Byte",
            "global::System.SByte" => "SByte",
            "global::System.Int16" => "Int16",
            "global::System.UInt16" => "UInt16",
            "global::System.Int32" => "Int32",
            "global::System.UInt32" => "UInt32",
            "global::System.Int64" => "Int64",
            "global::System.UInt64" => "UInt64",
            "global::System.Single" => "Single",
            "global::System.Double" => "Double",
            "global::System.Boolean" => "Boolean",
            "global::System.Char" => "Char",
            "global::System.String" => "String",
            _ => SanitizeKindName(type.Name)
        };
    }

    private static string SanitizeKindName(string name) =>
        name.Replace(".", "_").Replace("<", "").Replace(">", "").Replace("?", "").Replace("[]", "Array");

    private static void GenerateTypedDataExtensions(SourceProductionContext context,
        List<InlineTypeInfo> types)
    {
        if (types.Count == 0) return;

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0105");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace Origo.Core.Snd.Metadata;");
        sb.AppendLine();

        GenerateKindMap(sb, types);
        sb.AppendLine();
        GenerateStaticCtor(sb, types);
        sb.AppendLine();
        GenerateStringConversion(sb);
        sb.AppendLine();
        GenerateAsMethods(sb, types);
        sb.AppendLine();
        GenerateTryGetMethods(sb, types);
        sb.AppendLine();
        GenerateImplicitConversions(sb, types);
        sb.AppendLine();
        GenerateTypedDataTypeMap(sb, types);
        sb.AppendLine();
        GenerateTypedDataObjectConverter(sb, types);
        sb.AppendLine();
        GenerateTypedDataFactory(sb, types);

        context.AddSource("TypedData.g.cs", sb.ToString());
    }

    private static void GenerateKindMap(StringBuilder sb, List<InlineTypeInfo> types)
    {
        sb.AppendLine("partial struct TypedData");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class KindMap");
        sb.AppendLine("    {");
        sb.AppendLine("        public const byte Null = 0;");

        byte idx = 1;
        foreach (var t in types)
        {
            var name = t.KindIndex ?? $"Kind{idx}";
            sb.AppendLine($"        public const byte {name} = {idx};");
            idx++;
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void GenerateStaticCtor(StringBuilder sb, List<InlineTypeInfo> types)
    {
        sb.AppendLine("partial struct TypedData");
        sb.AppendLine("{");
        sb.AppendLine("    static TypedData()");
        sb.AppendLine("    {");
        sb.AppendLine("        KindTypeMap[0] = typeof(object);");

        byte idx = 1;
        foreach (var t in types)
        {
            sb.AppendLine($"        KindTypeMap[{idx}] = typeof({t.ClrTypeName});");
            idx++;
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void GenerateStringConversion(StringBuilder sb)
    {
        sb.AppendLine("partial struct TypedData");
        sb.AppendLine("{");
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public string? AsString() => (string?)_ref;");
        sb.AppendLine();
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public bool TryGetString(out string? value)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_kind == KindMap.String) { value = (string?)_ref; return true; }");
        sb.AppendLine("        value = null; return false;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void GenerateAsMethods(StringBuilder sb, List<InlineTypeInfo> types)
    {
        var inlineTypes = types.Where(t => t.FitsInline && !t.IsReferenceType).ToList();
        if (inlineTypes.Count == 0) return;

        sb.AppendLine("partial struct TypedData");
        sb.AppendLine("{");

        foreach (var t in inlineTypes)
        {
            var kind = t.KindIndex ?? t.ClrTypeName;
            var returnType = t.ClrTypeName;
            var methodName = $"As{t.KindIndex}";

            sb.AppendLine($"    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    internal {returnType} {methodName}()");
            sb.AppendLine("    {");

            if (t.SpecialType == SpecialType.System_Single)
            {
                sb.AppendLine("        return BitConverter.Int32BitsToSingle((int)_inlineBits);");
            }
            else if (t.SpecialType == SpecialType.System_Double)
            {
                sb.AppendLine("        return BitConverter.Int64BitsToDouble(_inlineBits);");
            }
            else if (t.SpecialType == SpecialType.System_Boolean)
            {
                sb.AppendLine("        return _inlineBits != 0;");
            }
            else if (t.SpecialType == SpecialType.System_Char)
            {
                sb.AppendLine("        return (char)(ushort)_inlineBits;");
            }
            else
            {
                sb.AppendLine($"        return ({returnType})_inlineBits;");
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
    }

    private static void GenerateTryGetMethods(StringBuilder sb, List<InlineTypeInfo> types)
    {
        var inlineTypes = types.Where(t => t.FitsInline && !t.IsReferenceType).ToList();
        if (inlineTypes.Count == 0) return;

        sb.AppendLine("partial struct TypedData");
        sb.AppendLine("{");

        foreach (var t in inlineTypes)
        {
            var kind = t.KindIndex ?? t.ClrTypeName;
            var returnType = t.ClrTypeName;
            var methodName = $"TryGet{t.KindIndex}";

            sb.AppendLine($"    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public bool {methodName}(out {returnType} value)");
            sb.AppendLine("    {");
            sb.AppendLine($"        if (_kind == KindMap.{kind})");
            sb.AppendLine("        {");

            if (t.SpecialType == SpecialType.System_Single)
            {
                sb.AppendLine("            value = BitConverter.Int32BitsToSingle((int)_inlineBits);");
            }
            else if (t.SpecialType == SpecialType.System_Double)
            {
                sb.AppendLine("            value = BitConverter.Int64BitsToDouble(_inlineBits);");
            }
            else if (t.SpecialType == SpecialType.System_Boolean)
            {
                sb.AppendLine("            value = _inlineBits != 0;");
            }
            else if (t.SpecialType == SpecialType.System_Char)
            {
                sb.AppendLine("            value = (char)(ushort)_inlineBits;");
            }
            else
            {
                sb.AppendLine($"            value = ({returnType})_inlineBits;");
            }

            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
            sb.AppendLine($"        value = default;");
            sb.AppendLine("        return false;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
    }

    private static void GenerateImplicitConversions(StringBuilder sb, List<InlineTypeInfo> types)
    {
        var inlineTypes = types.Where(t => t.FitsInline).ToList();
        if (inlineTypes.Count == 0) return;

        sb.AppendLine("partial struct TypedData");
        sb.AppendLine("{");

        byte idx = 1;
        foreach (var t in inlineTypes)
        {
            var kind = t.KindIndex ?? $"Kind{idx}";
            var typeName = t.ClrTypeName;

            sb.AppendLine($"    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public static explicit operator TypedData({typeName} value)");
            sb.AppendLine("    {");

            if (t.SpecialType == SpecialType.System_String)
            {
                sb.AppendLine($"        return new TypedData(KindMap.{kind}, 0, value);");
            }
            else if (t.SpecialType == SpecialType.System_Single)
            {
                sb.AppendLine($"        return new TypedData(KindMap.{kind}, BitConverter.SingleToInt32Bits(value), null);");
            }
            else if (t.SpecialType == SpecialType.System_Double)
            {
                sb.AppendLine($"        return new TypedData(KindMap.{kind}, BitConverter.DoubleToInt64Bits(value), null);");
            }
            else if (t.SpecialType == SpecialType.System_Boolean)
            {
                sb.AppendLine($"        return new TypedData(KindMap.{kind}, value ? 1 : 0, null);");
            }
            else if (t.SpecialType == SpecialType.System_Char)
            {
                sb.AppendLine($"        return new TypedData(KindMap.{kind}, value, null);");
            }
            else if (t.SpecialType == SpecialType.System_UInt32 || t.SpecialType == SpecialType.System_UInt64)
            {
                sb.AppendLine($"        return new TypedData(KindMap.{kind}, (long)value, null);");
            }
            else
            {
                sb.AppendLine($"        return new TypedData(KindMap.{kind}, value, null);");
            }

            sb.AppendLine("    }");
            sb.AppendLine();

            idx++;
        }

        sb.AppendLine("}");
    }

    private static void GenerateTypedDataTypeMap(StringBuilder sb, List<InlineTypeInfo> types)
    {
        sb.AppendLine("internal static class TypedDataTypeMap");
        sb.AppendLine("{");

        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public static byte GetKindForType(Type type)");
        sb.AppendLine("    {");

        byte idx = 1;
        foreach (var t in types)
        {
            sb.AppendLine($"        if (type == typeof({t.ClrTypeName})) return {idx};");
            idx++;
        }

        sb.AppendLine("        return 0;");
        sb.AppendLine("    }");

        sb.AppendLine("}");
    }

    private static void GenerateTypedDataObjectConverter(StringBuilder sb, List<InlineTypeInfo> types)
    {
        sb.AppendLine("internal static class TypedDataObjectConverter");
        sb.AppendLine("{");

        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public static object? ToObject(TypedData td)");
        sb.AppendLine("    {");

        sb.AppendLine("        switch (td._kind)");
        sb.AppendLine("        {");

        sb.AppendLine("            case 0: return null;");

        byte idx = 1;
        foreach (var t in types)
        {
            var kind = t.KindIndex ?? $"Kind{idx}";
            if (t.IsReferenceType)
            {
                sb.AppendLine($"            case {idx}: return td._ref;");
            }
            else if (t.FitsInline)
            {
                var methodName = $"As{t.KindIndex}";
                sb.AppendLine($"            case {idx}: return td.{methodName}();");
            }

            idx++;
        }

        sb.AppendLine("            default: return td._ref;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public static (long inlineBits, object? refValue) FromObject(byte kind, object value)");
        sb.AppendLine("    {");

        sb.AppendLine("        switch (kind)");
        sb.AppendLine("        {");

        idx = 1;
        foreach (var t in types)
        {
            if (t.IsReferenceType)
            {
                sb.AppendLine($"            case {idx}: return (0, value);");
            }
            else if (t.FitsInline)
            {
                if (t.SpecialType == SpecialType.System_Single)
                {
                    sb.AppendLine($"            case {idx}: return (BitConverter.SingleToInt32Bits((float)value), null);");
                }
                else if (t.SpecialType == SpecialType.System_Double)
                {
                    sb.AppendLine($"            case {idx}: return (BitConverter.DoubleToInt64Bits((double)value), null);");
                }
                else if (t.SpecialType == SpecialType.System_Boolean)
                {
                    sb.AppendLine($"            case {idx}: return ((bool)value ? 1 : 0, null);");
                }
                else
                {
                    var castExpr = GetFromObjectCastExpr(t);
                    sb.AppendLine($"            case {idx}: return ({castExpr}, null);");
                }
            }

            idx++;
        }

        sb.AppendLine("            default: return (0, value);");
        sb.AppendLine("        }");
        sb.AppendLine("    }");

        sb.AppendLine("}");
    }

    private static void GenerateTypedDataFactory(StringBuilder sb, List<InlineTypeInfo> types)
    {
        sb.AppendLine("internal static class TypedDataFactory<T>");
        sb.AppendLine("{");

        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public static TypedData Create(T value)");
        sb.AppendLine("    {");

        byte idx = 1;
        foreach (var t in types)
        {
            var clrName = t.ClrTypeName;

            sb.AppendLine($"        if (typeof(T) == typeof({clrName}))");
            sb.AppendLine("        {");

            if (t.IsReferenceType)
            {
                sb.AppendLine($"            return new TypedData({idx}, 0, value);");
            }
            else if (t.FitsInline)
            {
                var localType = GetFactoryLocalType(t);
                var extractExpr = GetFactoryExtractExpr(t);
                sb.AppendLine($"            {localType} local = {extractExpr};");
                var bitsExpr = GetFactoryBitsExpr(t);
                sb.AppendLine($"            return new TypedData({idx}, {bitsExpr}, null);");
            }

            sb.AppendLine("        }");

            idx++;
        }

        sb.AppendLine("        return new TypedData(255, 0, value);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public static bool TryExtract(TypedData source, out T value)");
        sb.AppendLine("    {");

        idx = 1;
        foreach (var t in types)
        {
            var clrName = t.ClrTypeName;

            sb.AppendLine($"        if (typeof(T) == typeof({clrName}) && source._kind == {idx})");
            sb.AppendLine("        {");

            if (t.IsReferenceType)
            {
                sb.AppendLine("            if (source._ref is T t) { value = t; return true; }");
            }
            else if (t.FitsInline)
            {
                var localType = GetFactoryLocalType(t);
                var readExpr = GetFactoryReadFromBitsExpr(t);
                sb.AppendLine($"            {localType} local = {readExpr};");
                sb.AppendLine($"            value = Unsafe.As<{localType}, T>(ref local);");
                sb.AppendLine("            return true;");
            }

            sb.AppendLine("        }");

            idx++;
        }

        sb.AppendLine("        if (source._ref is T t2) { value = t2; return true; }");
        sb.AppendLine("        value = default!;");
        sb.AppendLine("        return false;");
        sb.AppendLine("    }");

        sb.AppendLine("}");
    }

    private static string GetFactoryLocalType(InlineTypeInfo t)
    {
        return t.SpecialType switch
        {
            SpecialType.System_Byte => "byte",
            SpecialType.System_SByte => "sbyte",
            SpecialType.System_Int16 => "short",
            SpecialType.System_UInt16 => "ushort",
            SpecialType.System_Int32 => "int",
            SpecialType.System_UInt32 => "uint",
            SpecialType.System_Int64 => "long",
            SpecialType.System_UInt64 => "ulong",
            SpecialType.System_Single => "float",
            SpecialType.System_Double => "double",
            SpecialType.System_Boolean => "bool",
            SpecialType.System_Char => "char",
            _ => "long"
        };
    }

    private static string GetFactoryExtractExpr(InlineTypeInfo t)
    {
        return t.SpecialType switch
        {
            SpecialType.System_Byte => "Unsafe.As<T, byte>(ref value)",
            SpecialType.System_SByte => "Unsafe.As<T, sbyte>(ref value)",
            SpecialType.System_Int16 => "Unsafe.As<T, short>(ref value)",
            SpecialType.System_UInt16 => "Unsafe.As<T, ushort>(ref value)",
            SpecialType.System_Int32 => "Unsafe.As<T, int>(ref value)",
            SpecialType.System_UInt32 => "Unsafe.As<T, uint>(ref value)",
            SpecialType.System_Int64 => "Unsafe.As<T, long>(ref value)",
            SpecialType.System_UInt64 => "Unsafe.As<T, ulong>(ref value)",
            SpecialType.System_Single => "Unsafe.As<T, float>(ref value)",
            SpecialType.System_Double => "Unsafe.As<T, double>(ref value)",
            SpecialType.System_Boolean => "Unsafe.As<T, bool>(ref value)",
            SpecialType.System_Char => "Unsafe.As<T, char>(ref value)",
            _ => "Unsafe.As<T, long>(ref value)"
        };
    }

    private static string GetFactoryBitsExpr(InlineTypeInfo t)
    {
        return t.SpecialType switch
        {
            SpecialType.System_Single => "BitConverter.SingleToInt32Bits(local)",
            SpecialType.System_Double => "BitConverter.DoubleToInt64Bits(local)",
            SpecialType.System_Boolean => "local ? 1 : 0",
            SpecialType.System_UInt32 or SpecialType.System_UInt64 => "(long)local",
            _ => "local"
        };
    }

    private static string GetFactoryReadFromBitsExpr(InlineTypeInfo t)
    {
        return t.SpecialType switch
        {
            SpecialType.System_Single => "BitConverter.Int32BitsToSingle((int)source._inlineBits)",
            SpecialType.System_Double => "BitConverter.Int64BitsToDouble(source._inlineBits)",
            SpecialType.System_Boolean => "source._inlineBits != 0",
            _ => $"({GetFactoryLocalType(t)})source._inlineBits"
        };
    }

    private static string GetFromObjectCastExpr(InlineTypeInfo t)
    {
        return t.SpecialType switch
        {
            SpecialType.System_Byte => "(long)(byte)value",
            SpecialType.System_SByte => "(long)(sbyte)value",
            SpecialType.System_Int16 => "(long)(short)value",
            SpecialType.System_UInt16 => "(long)(ushort)value",
            SpecialType.System_Int32 => "(long)(int)value",
            SpecialType.System_UInt32 => "(long)(uint)value",
            SpecialType.System_Int64 => "(long)value",
            SpecialType.System_UInt64 => "(long)(ulong)value",
            SpecialType.System_Char => "(long)(char)value",
            _ => "(long)value"
        };
    }

    private sealed class InlineTypeInfo
    {
        public string? KindIndex { get; set; }
        public string FullTypeName { get; set; } = string.Empty;
        public string ClrTypeName { get; set; } = string.Empty;
        public bool IsReferenceType { get; set; }
        public SpecialType SpecialType { get; set; }
        public bool FitsInline { get; set; }
        public ITypeSymbol TypeSymbol { get; set; } = null!;
    }
}
