using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;

namespace Origo.SourceGeneration;

public sealed partial class TypedDataGenerator
{
    private static void GenerateAdapterAssembly(SourceProductionContext context, List<InlineTypeInfo> types)
    {
        var sb = new SourceBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0105");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine("using Origo.Core.Snd.Metadata;");
        sb.AppendLine();

        GenerateAdapterExtensionMethods(sb, types);
        sb.AppendLine();
        GenerateAdapterKindRegistration(sb, types);
        sb.AppendLine();
        GenerateAdapterConverterRegistration(sb, types);
        sb.AppendLine();
        GenerateAdapterTypeMapRegistration(sb, types);

        context.AddSource("TypedData.g.cs", sb.ToString());
    }

    private static void GenerateAdapterKindRegistration(SourceBuilder sb, List<InlineTypeInfo> types)
    {
        sb.AppendLine("internal static class TypedDataAdapterKindRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");

        foreach (var t in types)
        {
            sb.AppendLine($"        TypedData.RegisterKind({t.KindValue}, typeof({t.ClrTypeName}));");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void GenerateAdapterConverterRegistration(SourceBuilder sb, List<InlineTypeInfo> types)
    {
        sb.AppendLine("internal static class TypedDataAdapterConverterRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        TypedDataLayeredRegistry.RegisterFromObjectFallback(AdapterFromObject);");
        sb.AppendLine("        TypedDataLayeredRegistry.RegisterToObjectFallback(AdapterToObject);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    private static (long inlineBits, object? refValue)? AdapterFromObject(byte kind, object value)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (kind)");
        sb.AppendLine("        {");

        foreach (var t in types)
        {
            sb.AppendLine($"            case {t.KindValue}: return (0, value);");
        }

        sb.AppendLine("            default: return null;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    private static object? AdapterToObject(TypedData td)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (td._kind)");
        sb.AppendLine("        {");

        foreach (var t in types)
        {
            sb.AppendLine($"            case {t.KindValue}: return td._ref;");
        }

        sb.AppendLine("            default: return null;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void GenerateAdapterTypeMapRegistration(SourceBuilder sb, List<InlineTypeInfo> types)
    {
        sb.AppendLine("internal static class TypedDataAdapterTypeMapRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        TypedDataLayeredRegistry.RegisterKindResolver(ResolveKind);");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    private static byte ResolveKind(Type type)");
        sb.AppendLine("    {");

        foreach (var t in types)
        {
            sb.AppendLine($"        if (type == typeof({t.ClrTypeName})) return {t.KindValue};");
        }

        sb.AppendLine("        return 0;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void GenerateAdapterExtensionMethods(SourceBuilder sb, List<InlineTypeInfo> types)
    {
        var refTypes = types.Where(t => t.IsReferenceType).ToList();
        var valueTypes = types.Where(t => !t.IsReferenceType).ToList();

        if (refTypes.Count == 0 && valueTypes.Count == 0) return;

        // Internal: the adapter accessors mirror the home assembly's internal
        // AsXxx methods — they are unguarded (no kind check), so exposing them
        // publicly would let business code read a wrong type's bits or throw
        // opaque cast exceptions. Business reads go through TryGetXxx /
        // ISndEntity.TryGetData<T>.
        sb.AppendLine("internal static class TypedDataLayeredExtensions");
        sb.AppendLine("{");

        foreach (var t in refTypes)
        {
            sb.AppendLine($"    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public static {t.ClrTypeName}? As{t.KindIndex}(this TypedData td)");
            sb.AppendLine("    {");
            sb.AppendLine($"        return ({t.ClrTypeName}?)td._ref;");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine($"    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public static bool TryGet{t.KindIndex}(this TypedData td, out {t.ClrTypeName}? value)");
            sb.AppendLine("    {");
            sb.AppendLine($"        if (td._kind == {t.KindValue})");
            sb.AppendLine("        {");
            sb.AppendLine($"            value = ({t.ClrTypeName}?)td._ref;");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
            sb.AppendLine("        value = default;");
            sb.AppendLine("        return false;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        foreach (var t in valueTypes)
        {
            sb.AppendLine($"    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public static {t.ClrTypeName} As{t.KindIndex}(this TypedData td)");
            sb.AppendLine("    {");
            sb.AppendLine($"        return ({t.ClrTypeName})td._ref!;");
            sb.AppendLine("    }");
            sb.AppendLine();

            sb.AppendLine($"    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public static bool TryGet{t.KindIndex}(this TypedData td, out {t.ClrTypeName} value)");
            sb.AppendLine("    {");
            sb.AppendLine($"        if (td._kind == {t.KindValue} && td._ref is {t.ClrTypeName} v)");
            sb.AppendLine("        {");
            sb.AppendLine("            value = v;");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
            sb.AppendLine("        value = default;");
            sb.AppendLine("        return false;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
    }
}
