using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Origo.SourceGeneration;

public sealed partial class TypedDataGenerator
{
    private static void GenerateHomeAssembly(SourceProductionContext context, List<InlineTypeInfo> types)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0105");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Runtime.CompilerServices;");
        sb.AppendLine();
        sb.AppendLine("namespace Origo.Core.Snd.Metadata;");
        sb.AppendLine();

        GenerateKindMap(sb, types);
        sb.AppendLine();
        GenerateHomeKindRegistration(sb, types);
        sb.AppendLine();
        if (types.Any(t => t.SpecialType == SpecialType.System_String))
        {
            sb.AppendLine();
            GenerateStringConversion(sb);
        }
        GenerateIsProperties(sb, types);
        sb.AppendLine();
        GenerateAsMethods(sb, types);
        sb.AppendLine();
        GenerateTryGetMethods(sb, types);
        sb.AppendLine();
        GenerateImplicitConversions(sb, types);
        sb.AppendLine();
        GenerateTypedDataTypeMap(sb, types);
        sb.AppendLine();
        GenerateTypedDataObjectConverter(sb, types);
        sb.AppendLine();
        GenerateTypedDataFactory(sb, types);

        context.AddSource("TypedData.g.cs", sb.ToString());
    }

    private static void GenerateKindMap(StringBuilder sb, List<InlineTypeInfo> types)
    {
        sb.AppendLine("partial struct TypedData");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class KindMap");
        sb.AppendLine("    {");
        sb.AppendLine("        public const byte Null = 0;");

        foreach (var t in types)
        {
            sb.AppendLine($"        public const byte {t.KindIndex} = {t.KindValue};");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void GenerateHomeKindRegistration(StringBuilder sb, List<InlineTypeInfo> types)
    {
        sb.AppendLine("internal static class TypedDataHomeKindRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    [ModuleInitializer]");
        sb.AppendLine("    internal static void Initialize()");
        sb.AppendLine("    {");
        sb.AppendLine("        TypedData.RegisterKind(0, typeof(object));");

        foreach (var t in types)
        {
            sb.AppendLine($"        TypedData.RegisterKind({t.KindValue}, typeof({t.ClrTypeName}));");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void GenerateStringConversion(StringBuilder sb)
    {
        sb.AppendLine("partial struct TypedData");
        sb.AppendLine("{");
        sb.AppendLine("    internal readonly bool IsString => _kind == KindMap.String;");
        sb.AppendLine();
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public readonly string? AsString() => (string?)_ref;");
        sb.AppendLine();
        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public readonly bool TryGetString(out string value)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (_kind == KindMap.String) { value = Unsafe.As<string>(_ref)!; return true; }");
        sb.AppendLine("        value = null!; return false;");
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void GenerateIsProperties(StringBuilder sb, List<InlineTypeInfo> types)
    {
        sb.AppendLine("partial struct TypedData");
        sb.AppendLine("{");

        foreach (var t in types)
        {
            if (t.IsReferenceType) continue;
            sb.AppendLine($"    internal readonly bool Is{t.KindIndex} => _kind == KindMap.{t.KindIndex};");
            sb.AppendLine();
        }

        sb.AppendLine("}");
    }

    private static void GenerateAsMethods(StringBuilder sb, List<InlineTypeInfo> types)
    {
        var inlineTypes = types.Where(t => t.FitsInline).ToList();
        if (inlineTypes.Count == 0) return;

        sb.AppendLine("partial struct TypedData");
        sb.AppendLine("{");

        foreach (var t in inlineTypes)
        {
            var returnType = t.ClrTypeName;
            var methodName = $"As{t.KindIndex}";

            sb.AppendLine($"    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    internal readonly {returnType} {methodName}()");
            sb.AppendLine("    {");
            sb.AppendLine($"        {ReadInlineBitsExpr(t)}");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
    }

    private static void GenerateTryGetMethods(StringBuilder sb, List<InlineTypeInfo> types)
    {
        var inlineTypes = types.Where(t => t.FitsInline).ToList();
        if (inlineTypes.Count == 0) return;

        sb.AppendLine("partial struct TypedData");
        sb.AppendLine("{");

        foreach (var t in inlineTypes)
        {
            var returnType = t.ClrTypeName;
            var methodName = $"TryGet{t.KindIndex}";

            sb.AppendLine($"    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public readonly bool {methodName}(out {returnType} value)");
            sb.AppendLine("    {");
            sb.AppendLine($"        if (_kind == KindMap.{t.KindIndex})");
            sb.AppendLine("        {");
            sb.AppendLine($"            value = {ReadInlineBitsValueExpr(t)};");
            sb.AppendLine("            return true;");
            sb.AppendLine("        }");
            sb.AppendLine($"        value = default;");
            sb.AppendLine("        return false;");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
    }

    private static string ReadInlineBitsExpr(InlineTypeInfo t) =>
        $"return {ReadInlineBitsValueExpr(t)};";

    private static string ReadInlineBitsValueExpr(InlineTypeInfo t)
    {
        return t.SpecialType switch
        {
            SpecialType.System_Single => "BitConverter.Int32BitsToSingle((int)_inlineBits)",
            SpecialType.System_Double => "BitConverter.Int64BitsToDouble(_inlineBits)",
            SpecialType.System_Boolean => "_inlineBits != 0",
            SpecialType.System_Char => "(char)(ushort)_inlineBits",
            _ => $"({t.ClrTypeName})_inlineBits"
        };
    }

    private static void GenerateImplicitConversions(StringBuilder sb, List<InlineTypeInfo> types)
    {
        var inlineTypes = types.Where(t => t.FitsInline).ToList();
        if (inlineTypes.Count == 0) return;

        sb.AppendLine("partial struct TypedData");
        sb.AppendLine("{");

        foreach (var t in inlineTypes)
        {
            var typeName = t.ClrTypeName;

            sb.AppendLine($"    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
            sb.AppendLine($"    public static explicit operator TypedData({typeName} value)");
            sb.AppendLine("    {");
            sb.AppendLine($"        return new TypedData(KindMap.{t.KindIndex}, {PackInlineBitsExpr(t, "value")}, null);");
            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
    }

    private static string PackInlineBitsExpr(InlineTypeInfo t, string operand)
    {
        return t.SpecialType switch
        {
            SpecialType.System_Single => $"BitConverter.SingleToInt32Bits({operand})",
            SpecialType.System_Double => $"BitConverter.DoubleToInt64Bits({operand})",
            SpecialType.System_Boolean => $"{operand} ? 1 : 0",
            SpecialType.System_UInt32 or SpecialType.System_UInt64 => $"(long){operand}",
            _ => operand
        };
    }

    private static string FromObjectBitsExpr(InlineTypeInfo t)
    {
        return t.SpecialType switch
        {
            SpecialType.System_Single => "BitConverter.SingleToInt32Bits((float)value)",
            SpecialType.System_Double => "BitConverter.DoubleToInt64Bits((double)value)",
            SpecialType.System_Boolean => "(bool)value ? 1 : 0",
            SpecialType.System_Byte => "(long)(byte)value",
            SpecialType.System_SByte => "(long)(sbyte)value",
            SpecialType.System_Int16 => "(long)(short)value",
            SpecialType.System_UInt16 => "(long)(ushort)value",
            SpecialType.System_Int32 => "(long)(int)value",
            SpecialType.System_UInt32 => "(long)(uint)value",
            SpecialType.System_Int64 => "(long)value",
            SpecialType.System_UInt64 => "(long)(ulong)value",
            SpecialType.System_Char => "(long)(char)value",
            _ => "(long)value"
        };
    }

    private static void GenerateTypedDataTypeMap(StringBuilder sb, List<InlineTypeInfo> types)
    {
        sb.AppendLine("internal static class TypedDataTypeMap");
        sb.AppendLine("{");

        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public static byte GetKindForType(Type type)");
        sb.AppendLine("    {");

        foreach (var t in types)
        {
            sb.AppendLine($"        if (type == typeof({t.ClrTypeName})) return {t.KindValue};");
        }

        sb.AppendLine("        var kind = TypedDataLayeredRegistry.ResolveKind(type);");
        sb.AppendLine("        if (kind != 0) return kind;");
        sb.AppendLine("        return 0;");
        sb.AppendLine("    }");

        sb.AppendLine("}");
    }

    private static void GenerateTypedDataObjectConverter(StringBuilder sb, List<InlineTypeInfo> types)
    {
        sb.AppendLine("internal static class TypedDataObjectConverter");
        sb.AppendLine("{");

        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public static object? ToObject(TypedData td)");
        sb.AppendLine("    {");

        sb.AppendLine("        switch (td._kind)");
        sb.AppendLine("        {");
        sb.AppendLine("            case 0: return null;");

        foreach (var t in types)
        {
            if (t.IsReferenceType)
                sb.AppendLine($"            case {t.KindValue}: return td._ref;");
            else
                sb.AppendLine($"            case {t.KindValue}: return td.As{t.KindIndex}();");
        }

        sb.AppendLine("        }");
        sb.AppendLine("        var obj = TypedDataLayeredRegistry.ResolveToObject(td);");
        sb.AppendLine("        if (obj is not null) return obj;");
        sb.AppendLine("        return td._ref;");
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]");
        sb.AppendLine("    public static (long inlineBits, object? refValue) FromObject(byte kind, object value)");
        sb.AppendLine("    {");

        sb.AppendLine("        switch (kind)");
        sb.AppendLine("        {");

        foreach (var t in types)
        {
            if (t.IsReferenceType)
                sb.AppendLine($"            case {t.KindValue}: return (0, value);");
            else
                sb.AppendLine($"            case {t.KindValue}: return ({FromObjectBitsExpr(t)}, null);");
        }

        sb.AppendLine("        }");
        sb.AppendLine("        var result = TypedDataLayeredRegistry.ResolveFromObject(kind, value);");
        sb.AppendLine("        if (result.HasValue) return result.Value;");
        sb.AppendLine("        return (0, value);");
        sb.AppendLine("    }");

        sb.AppendLine("}");
    }
}
