using System.IO;
using System.Text.Json;
using Xunit;

namespace DocSyncTool.Tests;

public class GeneratorTests
{
    private static void WritePair(TestRepo repo, string pairId, int zhRevision, int enRevision, string? path = null)
    {
        path ??= "docs/" + pairId;
        repo.Write(path + ".zh.md", TestRepo.Header(pairId, zhRevision) + $"# {pairId} zh\n");
        repo.Write(path + ".en.md", TestRepo.Header(pairId, enRevision) + $"# {pairId} en\n");
    }

    [Fact]
    public void Generate_CreatesNavigationHub()
    {
        using var repo = TestRepo.Create();
        WritePair(repo, "README", 1, 1);

        Generator.Run(repo.LoadConfig());

        var hub = repo.Read("docs/README.md");
        Assert.Contains("auto-generated by DocSyncTool", hub);
        Assert.Contains("## 中文", hub);
        Assert.Contains("## English", hub);
        Assert.Contains("- [README](README.zh.md)", hub);
        Assert.Contains("- [README](README.en.md)", hub);
    }

    [Fact]
    public void Generate_CreatesStatusFileWithSyncedStatus()
    {
        using var repo = TestRepo.Create();
        WritePair(repo, "README", 3, 3);

        Generator.Run(repo.LoadConfig());

        var status = JsonSerializer.Deserialize<JsonElement>(repo.Read("docs/.sync-status.json"));
        var pair = status.GetProperty("pairs").GetProperty("README");
        Assert.Equal("synced", pair.GetProperty("status").GetString());
        Assert.Equal(3, pair.GetProperty("revisions").GetProperty("zh").GetInt32());
        Assert.Equal(3, pair.GetProperty("revisions").GetProperty("en").GetInt32());
    }

    [Fact]
    public void Generate_StatusFile_ZhAhead()
    {
        using var repo = TestRepo.Create();
        WritePair(repo, "README", 5, 4);

        Generator.Run(repo.LoadConfig());

        var status = JsonSerializer.Deserialize<JsonElement>(repo.Read("docs/.sync-status.json"));
        var pair = status.GetProperty("pairs").GetProperty("README");
        Assert.Equal("zh-ahead", pair.GetProperty("status").GetString());
    }

    [Fact]
    public void Generate_StatusFile_MissingEn()
    {
        using var repo = TestRepo.Create();
        repo.Write("docs/README.zh.md", TestRepo.Header("README") + "# zh\n");

        Generator.Run(repo.LoadConfig());

        var status = JsonSerializer.Deserialize<JsonElement>(repo.Read("docs/.sync-status.json"));
        var pair = status.GetProperty("pairs").GetProperty("README");
        Assert.Equal("missing-en", pair.GetProperty("status").GetString());
    }

    [Fact]
    public void Generate_IsIdempotent()
    {
        using var repo = TestRepo.Create();
        WritePair(repo, "README", 1, 1);
        WritePair(repo, "a/README", 1, 1);

        Generator.Run(repo.LoadConfig());
        var hub1 = repo.Read("docs/README.md");
        var status1 = repo.Read("docs/.sync-status.json");
        var nested1 = repo.Read("docs/a/README.md");

        Generator.Run(repo.LoadConfig());

        Assert.Equal(hub1, repo.Read("docs/README.md"));
        Assert.Equal(status1, repo.Read("docs/.sync-status.json"));
        Assert.Equal(nested1, repo.Read("docs/a/README.md"));
    }

    [Fact]
    public void Generate_IncludesSubdirectoryHubs()
    {
        using var repo = TestRepo.Create();
        WritePair(repo, "README", 1, 1);
        WritePair(repo, "a/b/README", 1, 1);

        Generator.Run(repo.LoadConfig());

        Assert.True(repo.Exists("docs/a/README.md"));
        Assert.True(repo.Exists("docs/a/b/README.md"));
        var rootHub = repo.Read("docs/README.md");
        Assert.Contains("- [a/](a/)", rootHub);
        var aHub = repo.Read("docs/a/README.md");
        Assert.Contains("- [b/](b/)", aHub);
        var bHub = repo.Read("docs/a/b/README.md");
        Assert.Contains("- [README](README.zh.md)", bHub);
        Assert.Contains("- [README](README.en.md)", bHub);
    }

    [Fact]
    public void Generate_DirectoryWithoutDocs_Skipped()
    {
        using var repo = TestRepo.Create();
        WritePair(repo, "README", 1, 1);

        Generator.Run(repo.LoadConfig());

        Assert.False(repo.Exists("docs/empty/README.md"));
    }

    [Fact]
    public void Generate_RemovesStaleHubOfDocLessDirectory()
    {
        using var repo = TestRepo.Create();
        WritePair(repo, "README", 1, 1);
        WritePair(repo, "ghost", 1, 1, path: "docs/ghost/README");

        Generator.Run(repo.LoadConfig());
        Assert.True(repo.Exists("docs/ghost/README.md"));

        // Delete the content files; the leftover auto-generated hub must be
        // removed on the next generate, and the ghost directory must not
        // appear in the parent hub.
        File.Delete(repo.Full("docs/ghost/README.zh.md"));
        File.Delete(repo.Full("docs/ghost/README.en.md"));

        Generator.Run(repo.LoadConfig());

        Assert.False(repo.Exists("docs/ghost/README.md"));
        Assert.DoesNotContain("ghost/", repo.Read("docs/README.md"));
    }

    [Fact]
    public void Generate_FilesWithoutMetadata_GetDerivedDefaults()
    {
        using var repo = TestRepo.Create();
        repo.Write("docs/orphan.zh.md", "# orphan\n");

        Generator.Run(repo.LoadConfig());

        var status = JsonSerializer.Deserialize<JsonElement>(repo.Read("docs/.sync-status.json"));
        var pair = status.GetProperty("pairs").GetProperty("orphan");
        Assert.Equal(1, pair.GetProperty("revisions").GetProperty("zh").GetInt32());
        Assert.Equal("missing-en", pair.GetProperty("status").GetString());
    }
}
