using System.IO;
using System.Text.Json;
using Xunit;

namespace DocSyncTool.Tests;

/// <summary>
///     Runs in a serialized collection because <see cref="ConsoleOutputCapture" />
///     redirects the process-global console streams.
/// </summary>
[Collection("DocSyncToolConsoleCapture")]
public class GeneratorTests
{
    [CollectionDefinition("DocSyncToolConsoleCapture", DisableParallelization = true)]
    public class DocSyncToolToolTestsDefinition
    {
    }

    private static void RunGenerator(Config config) =>
        ConsoleOutputCapture.Run(() => Generator.Run(config));

    private static void WritePair(TestRepo repo, string pairId, int zhRevision, int enRevision, string? path = null)
    {
        path ??= "docs/" + pairId;
        repo.Write(path + ".zh.md", TestRepo.Header(pairId, zhRevision) + $"# {pairId} zh\n");
        repo.Write(path + ".en.md", TestRepo.Header(pairId, enRevision) + $"# {pairId} en\n");
    }

    [Fact]
    public void Generate_CreatesNavigationHub()
    {
        using var repo = TestRepo.Create();
        WritePair(repo, "README", 1, 1);

        RunGenerator(repo.LoadConfig());

        var hub = repo.Read("docs/README.md");
        Assert.Contains("auto-generated by DocSyncTool", hub);
        Assert.Contains("## 中文", hub);
        Assert.Contains("## English", hub);
        Assert.Contains("- [README](README.zh.md)", hub);
        Assert.Contains("- [README](README.en.md)", hub);
    }

    [Fact]
    public void Generate_CreatesStatusFileWithSyncedStatus()
    {
        using var repo = TestRepo.Create();
        WritePair(repo, "README", 3, 3);

        RunGenerator(repo.LoadConfig());

        var status = JsonSerializer.Deserialize<JsonElement>(repo.Read("docs/.sync-status.json"));
        var pair = status.GetProperty("pairs").GetProperty("README");
        Assert.Equal("synced", pair.GetProperty("status").GetString());
        Assert.Equal(3, pair.GetProperty("revisions").GetProperty("zh").GetInt32());
        Assert.Equal(3, pair.GetProperty("revisions").GetProperty("en").GetInt32());
    }

    [Fact]
    public void Generate_StatusFile_ZhAhead()
    {
        using var repo = TestRepo.Create();
        WritePair(repo, "README", 5, 4);

        RunGenerator(repo.LoadConfig());

        var status = JsonSerializer.Deserialize<JsonElement>(repo.Read("docs/.sync-status.json"));
        var pair = status.GetProperty("pairs").GetProperty("README");
        Assert.Equal("zh-ahead", pair.GetProperty("status").GetString());
    }

    [Fact]
    public void Generate_StatusFile_MissingEn()
    {
        using var repo = TestRepo.Create();
        repo.Write("docs/README.zh.md", TestRepo.Header("README") + "# zh\n");

        RunGenerator(repo.LoadConfig());

        var status = JsonSerializer.Deserialize<JsonElement>(repo.Read("docs/.sync-status.json"));
        var pair = status.GetProperty("pairs").GetProperty("README");
        Assert.Equal("missing-en", pair.GetProperty("status").GetString());
    }

    [Fact]
    public void Generate_RevisionBump_RecordsPreviousRevisionAndStaysIdempotent()
    {
        using var repo = TestRepo.Create();
        WritePair(repo, "README", 1, 1);

        RunGenerator(repo.LoadConfig());
        var first = repo.Read("docs/.sync-status.json");

        repo.Write("docs/README.zh.md", TestRepo.Header("README", 2) + "# zh\n");
        repo.Write("docs/README.en.md", TestRepo.Header("README", 2) + "# en\n");
        RunGenerator(repo.LoadConfig());

        var status = JsonSerializer.Deserialize<JsonElement>(repo.Read("docs/.sync-status.json"));
        var pair = status.GetProperty("pairs").GetProperty("README");
        Assert.Equal(1, pair.GetProperty("previous_revisions").GetProperty("zh").GetInt32());
        Assert.Equal(1, pair.GetProperty("previous_revisions").GetProperty("en").GetInt32());

        RunGenerator(repo.LoadConfig());
        Assert.Equal(repo.Read("docs/.sync-status.json"), repo.Read("docs/.sync-status.json"));
        Assert.NotEqual(first, repo.Read("docs/.sync-status.json"));
    }

    [Fact]
    public void Generate_MalformedPreviousStatus_RebuildsSnapshot()
    {
        using var repo = TestRepo.Create();
        WritePair(repo, "README", 1, 1);
        repo.Write("docs/.sync-status.json", "{not-json");

        RunGenerator(repo.LoadConfig());

        var status = JsonSerializer.Deserialize<JsonElement>(repo.Read("docs/.sync-status.json"));
        Assert.Equal("synced", status.GetProperty("pairs").GetProperty("README").GetProperty("status").GetString());
    }

    [Fact]
    public void Generate_IsIdempotent()
    {
        using var repo = TestRepo.Create();
        WritePair(repo, "README", 1, 1);
        WritePair(repo, "a/README", 1, 1);

        RunGenerator(repo.LoadConfig());
        var hub1 = repo.Read("docs/README.md");
        var status1 = repo.Read("docs/.sync-status.json");
        var nested1 = repo.Read("docs/a/README.md");

        RunGenerator(repo.LoadConfig());

        Assert.Equal(hub1, repo.Read("docs/README.md"));
        Assert.Equal(status1, repo.Read("docs/.sync-status.json"));
        Assert.Equal(nested1, repo.Read("docs/a/README.md"));
    }

    [Fact]
    public void Generate_IncludesSubdirectoryHubs()
    {
        using var repo = TestRepo.Create();
        WritePair(repo, "README", 1, 1);
        WritePair(repo, "a/b/README", 1, 1);

        RunGenerator(repo.LoadConfig());

        Assert.True(repo.Exists("docs/a/README.md"));
        Assert.True(repo.Exists("docs/a/b/README.md"));
        var rootHub = repo.Read("docs/README.md");
        Assert.Contains("- [a/](a/)", rootHub);
        var aHub = repo.Read("docs/a/README.md");
        Assert.Contains("- [b/](b/)", aHub);
        var bHub = repo.Read("docs/a/b/README.md");
        Assert.Contains("- [README](README.zh.md)", bHub);
        Assert.Contains("- [README](README.en.md)", bHub);
    }

    [Fact]
    public void Generate_HonorsConfiguredLanguagesForSubdirectoryHubs()
    {
        // The configured language list is the source of truth for content
        // files. A directory containing only a newly configured language
        // (here "fr") must still appear in its parent navigation hub.
        using var repo = TestRepo.Create(["zh", "fr"]);
        repo.Write("docs/README.zh.md", TestRepo.Header("README") + "# root zh\n");
        repo.Write("docs/README.fr.md", TestRepo.Header("README") + "# root fr\n");
        repo.Write("docs/a/notes.fr.md", TestRepo.Header("a/notes") + "# notes fr\n");

        RunGenerator(repo.LoadConfig());

        var rootHub = repo.Read("docs/README.md");
        Assert.Contains("- [a/](a/)", rootHub);
        Assert.True(repo.Exists("docs/a/README.md"));
        var aHub = repo.Read("docs/a/README.md");
        Assert.Contains("- [notes](notes.fr.md)", aHub);
    }

    [Fact]
    public void Generate_DirectoryWithoutDocs_Skipped()
    {
        using var repo = TestRepo.Create();
        WritePair(repo, "README", 1, 1);

        RunGenerator(repo.LoadConfig());

        Assert.False(repo.Exists("docs/empty/README.md"));
    }

    [Fact]
    public void Generate_RemovesStaleHubOfDocLessDirectory()
    {
        using var repo = TestRepo.Create();
        WritePair(repo, "README", 1, 1);
        WritePair(repo, "ghost", 1, 1, path: "docs/ghost/README");

        RunGenerator(repo.LoadConfig());
        Assert.True(repo.Exists("docs/ghost/README.md"));

        // Delete the content files; the leftover auto-generated hub must be
        // removed on the next generate, and the ghost directory must not
        // appear in the parent hub.
        File.Delete(repo.Full("docs/ghost/README.zh.md"));
        File.Delete(repo.Full("docs/ghost/README.en.md"));

        RunGenerator(repo.LoadConfig());

        Assert.False(repo.Exists("docs/ghost/README.md"));
        Assert.DoesNotContain("ghost/", repo.Read("docs/README.md"));
    }

    [Fact]
    public void Generate_FilesWithoutMetadata_GetDerivedDefaults()
    {
        using var repo = TestRepo.Create();
        repo.Write("docs/orphan.zh.md", "# orphan\n");

        RunGenerator(repo.LoadConfig());

        var status = JsonSerializer.Deserialize<JsonElement>(repo.Read("docs/.sync-status.json"));
        var pair = status.GetProperty("pairs").GetProperty("orphan");
        Assert.Equal(1, pair.GetProperty("revisions").GetProperty("zh").GetInt32());
        Assert.Equal("missing-en", pair.GetProperty("status").GetString());
    }
}
