using System;
using System.IO;
using Xunit;

namespace DocSyncTool.Tests;

/// <summary>
/// Program.Main resolves the repo root from the current working directory, so
/// every test here switches the process CWD to an isolated TestRepo. The class
/// runs in a serialized collection because CWD is process-global state.
/// </summary>
[Collection("DocSyncToolProgramTests")]
public class ProgramTests
{
    [CollectionDefinition("DocSyncToolProgramTests", DisableParallelization = true)]
    public class DocSyncToolProgramTestsDefinition
    {
    }

    private static int RunIn(string root, params string[] args)
    {
        var previous = Environment.CurrentDirectory;
        try
        {
            Environment.CurrentDirectory = root;
            return Program.Main(args);
        }
        finally
        {
            Environment.CurrentDirectory = previous;
        }
    }

    private static int RunIn(TestRepo repo, params string[] args)
    {
        return RunIn(repo.Root, args);
    }
    [Fact]
    public void Main_NoArgs_ReturnsUsageExitCode()
    {
        using var repo = TestRepo.Create();
        Assert.Equal(1, RunIn(repo));
    }

    [Fact]
    public void Main_UnknownCommand_ReturnsUsageExitCode()
    {
        using var repo = TestRepo.Create();
        Assert.Equal(1, RunIn(repo, "bogus"));
    }

    [Fact]
    public void Main_Generate_ReturnsZeroAndWritesStatusFile()
    {
        using var repo = TestRepo.Create();
        repo.Write("docs/README.zh.md", TestRepo.Header("README") + "# zh\n");
        repo.Write("docs/README.en.md", TestRepo.Header("README") + "# en\n");

        Assert.Equal(0, RunIn(repo, "generate"));
        Assert.True(repo.Exists("docs/README.md"));
        Assert.True(repo.Exists("docs/.sync-status.json"));
    }

    [Fact]
    public void Main_Validate_FailureReturnsOne()
    {
        using var repo = TestRepo.Create();
        repo.Write("docs/README.zh.md", TestRepo.Header("README", 1) + "# zh\n");
        repo.Write("docs/README.en.md", TestRepo.Header("README", 2) + "# en\n");

        Assert.Equal(1, RunIn(repo, "validate"));
    }

    [Fact]
    public void Main_Validate_SuccessReturnsZero()
    {
        using var repo = TestRepo.Create();
        repo.Write("docs/README.zh.md", TestRepo.Header("README") + "# zh\n");
        repo.Write("docs/README.en.md", TestRepo.Header("README") + "# en\n");

        Assert.Equal(0, RunIn(repo, "validate"));
    }

    [Fact]
    public void Main_Init_MigratesAndValidates()
    {
        using var repo = TestRepo.Create(["zh"]);
        repo.Write("docs/README.md", "# Readme\n");

        Assert.Equal(0, RunIn(repo, "init"));
        Assert.True(repo.Exists("docs/README.zh.md"));
        Assert.Contains("auto-generated by DocSyncTool", repo.Read("docs/README.md"));
    }

    [Fact]
    public void Main_OutsideRepo_FatalExitCode()
    {
        var outside = Path.Combine(Path.GetTempPath(), "docsync-norepo-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(outside);
        try
        {
            Assert.Equal(2, RunIn(outside, "generate"));
        }
        finally
        {
            Directory.Delete(outside, true);
        }
    }
}
