using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace DocSyncTool;

internal static class Generator
{
    private const int _statusSchemaVersion = 2;
    private const string _autoRevisionReminderEn =
        "<!-- docsync-revision — managed automatically by DocSyncTool; DO NOT EDIT. -->";
    private const string _autoRevisionReminderZh =
        "<!-- docsync-revision — 由 DocSyncTool 根据 git 历史自动管理；请勿手改。 -->";

    private static readonly JsonSerializerOptions _jsonOptions = new()
    {
        WriteIndented = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping
    };

    public static void Run(Config config)
    {
        var docsRoot = config.DocsFullPath;
        var languages = config.Languages;
        var previousStatus = ReadPreviousStatus(config);

        var allFiles = new List<DocFile>();
        foreach (var lang in languages)
        {
            var pattern = $"*.{lang}.md";
            var files = Directory.GetFiles(docsRoot, pattern, SearchOption.AllDirectories);
            foreach (var file in files)
            {
                var relPath = Path.GetRelativePath(docsRoot, file).Replace('\\', '/');
                var docFile = new DocFile(file, relPath, lang);

                try
                {
                    var content = File.ReadAllText(file);
                    ParseMetadataQuick(docFile, content);
                    docFile.ContentHash = ContentHash.Compute(content);
                }
                catch
                {
                    // If parsing fails, still include the file with default values
                }

                allFiles.Add(docFile);
            }
        }

        var git = GitRepository.TryCreate(config.RepoRoot);
        if (git is not null)
            ApplyAutomaticRevisions(config, allFiles, previousStatus, git);

        var filesByDir = allFiles
            .GroupBy(f => Path.GetDirectoryName(f.RelativePath)?.Replace('\\', '/') ?? "")
            .ToDictionary(g => g.Key, g => g.ToList());

        var directories = GetAllDirectories(docsRoot);

        foreach (var dir in directories)
        {
            var dirRel = dir == "" ? "" : dir.Replace('\\', '/');
            filesByDir.TryGetValue(dirRel, out var dirFiles);
            dirFiles ??= [];

            var subDirs = GetSubDirectories(docsRoot, dir, languages);
            var hasContent = dirFiles.Count > 0 || subDirs.Count > 0;
            if (!hasContent)
            {
                // A directory whose docs were deleted leaves an auto-generated
                // README.md hub behind; remove it so the mirror does not
                // accumulate stale hubs (or ghost entries in parent hubs).
                var staleHub = Path.Combine(docsRoot, dir, "README.md");
                if (File.Exists(staleHub) && IsAutoGeneratedHub(staleHub))
                {
                    File.Delete(staleHub);
                    Console.WriteLine($"  REMOVED stale hub: {(string.IsNullOrEmpty(dirRel) ? "README.md" : $"{dirRel}/README.md")}");
                }

                continue;
            }

            var sb = new StringBuilder();
            sb.AppendLine("<!-- auto-generated by DocSyncTool. DO NOT EDIT. -->");
            sb.AppendLine();

            var displayPath = string.IsNullOrEmpty(dirRel) ? "docs" : $"docs/{dirRel}";
            sb.AppendLine(CultureInfo.InvariantCulture, $"# {displayPath}");
            sb.AppendLine();

            foreach (var lang in languages)
            {
                var langLabel = LangLabel(lang);
                sb.AppendLine(CultureInfo.InvariantCulture, $"## {langLabel}");

                var langFiles = dirFiles.Where(f => f.Language == lang).ToList();

                foreach (var file in langFiles.OrderBy(f => Path.GetFileName(f.RelativePath)))
                {
                    var name = Path.GetFileName(file.RelativePath);
                    var display = Path.GetFileNameWithoutExtension(name);
                    var lastDot = display.LastIndexOf('.');
                    if (lastDot >= 0)
                        display = display[..lastDot];

                    sb.AppendLine(CultureInfo.InvariantCulture, $"- [{display}]({name})");
                }

                foreach (var subDir in subDirs.OrderBy(d => d))
                {
                    var subName = subDir.Split('/').Last();
                    sb.AppendLine(CultureInfo.InvariantCulture, $"- [{subName}/]({subName}/)");
                }

                if (langFiles.Count == 0 && subDirs.Count == 0)
                    sb.AppendLine("- _(none)_");

                sb.AppendLine();
            }

            var readmePath = Path.Combine(docsRoot, dir, "README.md");
            var readmeDir = Path.GetDirectoryName(readmePath);
            if (readmeDir is not null && !Directory.Exists(readmeDir))
                Directory.CreateDirectory(readmeDir);

            var newContent = sb.ToString();
            var oldContent = File.Exists(readmePath) ? File.ReadAllText(readmePath) : null;
            var hubRel = string.IsNullOrEmpty(dirRel) ? "README.md" : $"{dirRel}/README.md";
            if (oldContent != newContent)
            {
                File.WriteAllText(readmePath, newContent);
                Console.WriteLine($"  GENERATED: {hubRel}");
            }
            else
            {
                Console.WriteLine($"  SKIPPED (unchanged): {hubRel}");
            }
        }

        GenerateStatusFile(config, allFiles, previousStatus);
    }

    private static void ApplyAutomaticRevisions(
        Config config,
        List<DocFile> allFiles,
        StatusFile? previousStatus,
        GitRepository git)
    {
        var tracker = new RevisionTracker(git);
        var plans = new List<RevisionPlan>(allFiles.Count);

        foreach (var file in allFiles)
        {
            var previousPair = GetPreviousPair(previousStatus, file.PairId);
            var oldRevision = 0;
            var hasPrevious = previousPair is not null
                && previousPair.Revisions.TryGetValue(file.Language, out oldRevision);

            if (!hasPrevious)
            {
                plans.Add(new RevisionPlan(file, 0, null, true, []));
                continue;
            }

            var oldHash = previousPair!.ContentHashes is not null
                && previousPair.ContentHashes.TryGetValue(file.Language, out var previousHash)
                    ? previousHash
                    : null;

            var content = File.ReadAllText(file.FullPath);
            var repoRelativePath = Path.GetRelativePath(config.RepoRoot, file.FullPath).Replace('\\', '/');
            List<DocContentEvent> events;
            if (oldHash is null)
            {
                // A schema 2 snapshot always records content hashes. A
                // hand-edited snapshot without hashes is re-anchored on this
                // run; no historical event can be reconstructed for it.
                events = [];
            }
            else
            {
                events = tracker.GetContentEvents(repoRelativePath, content, oldHash);
            }

            plans.Add(new RevisionPlan(file, oldRevision, oldHash, false, events));
        }

        var commitOrder = git.GetCommitTopologyOrder();
        foreach (var pair in plans.GroupBy(p => p.File.PairId))
        {
            var revisions = ComputePairRevisions([.. pair], commitOrder);
            foreach (var plan in pair)
            {
                var previousRevision = plan.File.Revision;
                plan.File.Revision = revisions[plan.File.Language];
                UpdateDocSyncHeaders(plan.File, previousRevision);
            }
        }
    }

    private static StatusPairEntry? GetPreviousPair(StatusFile? previousStatus, string pairId)
    {
        if (previousStatus is null)
            return null;

        previousStatus.Pairs.TryGetValue(pairId, out var entry);
        return entry;
    }

    private static Dictionary<string, int> ComputePairRevisions(
        List<RevisionPlan> plans,
        Dictionary<string, int> commitOrder)
    {
        var revisions = plans
            .Where(p => !p.IsNew)
            .ToDictionary(p => p.File.Language, p => p.OldRevision);

        var events = plans
            .Where(p => !p.IsNew)
            .SelectMany(p => p.Events.Select(e => new PairRevisionEvent(
                e.CommitSha,
                e.Timestamp,
                p.File.Language)))
            .OrderBy(e => GetCommitOrder(e.CommitSha, commitOrder))
            .ThenBy(e => e.Timestamp)
            .ThenBy(e => e.CommitSha ?? "")
            .ToList();

        foreach (var group in events.GroupBy(e => (e.CommitSha ?? "", e.Timestamp)))
        {
            if (revisions.Count == 0)
                continue;

            var maxBefore = revisions.Values.Max();
            var changedLanguages = group.Select(e => e.Language).Distinct().ToList();

            foreach (var language in changedLanguages)
            {
                // A stale side catching up (for example a translation commit)
                // adopts the pair's current revision instead of jumping ahead.
                // Editing the leading side, or editing both sides together,
                // advances the pair by one generation.
                revisions[language] = revisions[language] < maxBefore
                    ? maxBefore
                    : maxBefore + 1;
            }
        }

        var maxExisting = revisions.Count == 0 ? 0 : revisions.Values.Max();
        foreach (var plan in plans.Where(p => p.IsNew))
            revisions[plan.File.Language] = maxExisting == 0 ? 1 : maxExisting;

        return revisions;
    }

    private static void UpdateDocSyncHeaders(DocFile file, int previousRevision)
    {
        var content = File.ReadAllText(file.FullPath);
        var newContent = WithDocSyncHeaders(content, file.PairId, file.Revision, file.Language);

        if (string.Equals(content, newContent, StringComparison.Ordinal))
            return;

        File.WriteAllText(file.FullPath, newContent);
        if (previousRevision != file.Revision)
            Console.WriteLine($"  UPDATED REVISION: {file.RelativePath} ({previousRevision} -> {file.Revision})");
        else
            Console.WriteLine($"  UPDATED HEADER: {file.RelativePath}");
    }

    private static string WithDocSyncHeaders(string content, string pairId, int revision, string language)
    {
        var normalized = content.Replace("\r\n", "\n").Replace('\r', '\n');
        var lines = normalized.Split('\n');
        var body = lines
            .Where((line, index) => index >= 12 || !ContentHash.IsDocSyncMetadataLine(line.Trim()))
            .ToList();

        var header = new List<string>
        {
            $"<!-- docsync-pair: {pairId} -->",
            $"<!-- docsync-revision: {revision} -->",
            language == "zh" ? _autoRevisionReminderZh : _autoRevisionReminderEn
        };
        header.AddRange(body);

        return string.Join('\n', header);
    }

    private static List<string> GetAllDirectories(string docsRoot)
    {
        var dirs = new List<string> { "" };
        var allDirs = Directory.GetDirectories(docsRoot, "*", SearchOption.AllDirectories);
        foreach (var dir in allDirs)
        {
            var rel = Path.GetRelativePath(docsRoot, dir).Replace('\\', '/');
            dirs.Add(rel);
        }
        return [.. dirs.OrderBy(d => d.Length).ThenBy(d => d)];
    }

    private static List<string> GetSubDirectories(
        string docsRoot,
        string parentRel,
        List<string> languages)
    {
        var parentDir = string.IsNullOrEmpty(parentRel) ? docsRoot : Path.Combine(docsRoot, parentRel);
        if (!Directory.Exists(parentDir))
            return [];

        var subDirs = Directory.GetDirectories(parentDir);
        return [.. subDirs
            .Select(d => Path.GetRelativePath(docsRoot, d).Replace('\\', '/'))
            .Where(d => HasDocFiles(Path.Combine(docsRoot, d), languages))
            .OrderBy(d => d)];
    }

    private static bool HasDocFiles(string fullPath, List<string> languages)
    {
        if (!Directory.Exists(fullPath))
            return false;

        // Only configured-language content files count; a leftover auto-
        // generated README.md hub must not keep a doc-less directory alive
        // in the parent hub's subdirectory list.
        var mdFiles = Directory.GetFiles(fullPath, "*.md", SearchOption.AllDirectories);
        return mdFiles.Any(f =>
        {
            var name = Path.GetFileName(f);
            return languages.Any(lang =>
                name.EndsWith($".{lang}.md", StringComparison.OrdinalIgnoreCase));
        });
    }

    private static string LangLabel(string lang)
    {
        return lang switch
        {
            "zh" => "中文",
            "en" => "English",
            _ => lang
        };
    }

    private static bool IsAutoGeneratedHub(string path)
    {
        try
        {
            var firstLine = File.ReadLines(path).FirstOrDefault() ?? string.Empty;
            return firstLine.Contains("auto-generated by DocSyncTool", StringComparison.Ordinal);
        }
        catch
        {
            return false;
        }
    }

    private static void ParseMetadataQuick(DocFile docFile, string content)
    {
        var lines = content.Split('\n');
        foreach (var line in lines.Take(5))
        {
            var trimmed = line.Trim();

            if (trimmed.StartsWith("<!-- docsync-pair:", StringComparison.OrdinalIgnoreCase)
                && string.IsNullOrEmpty(docFile.PairId))
            {
                var start = trimmed.IndexOf(':', StringComparison.Ordinal);
                var end = trimmed.LastIndexOf("-->", StringComparison.Ordinal);
                if (start >= 0 && end > start)
                    docFile.PairId = trimmed[(start + 1)..end].Trim();
            }

            if (trimmed.StartsWith("<!-- docsync-revision:", StringComparison.OrdinalIgnoreCase)
                && docFile.Revision == 0)
            {
                var start = trimmed.IndexOf(':', StringComparison.Ordinal);
                var end = trimmed.LastIndexOf("-->", StringComparison.Ordinal);
                if (start >= 0 && end > start
                    && int.TryParse(trimmed[(start + 1)..end].Trim(), out var rev))
                    docFile.Revision = rev;
            }
        }

        if (string.IsNullOrEmpty(docFile.PairId))
            docFile.PairId = DocFile.DerivePairId(docFile.RelativePath);

        if (docFile.Revision == 0)
            docFile.Revision = 1;
    }

    private static void GenerateStatusFile(
        Config config,
        List<DocFile> allFiles,
        StatusFile? previousStatus)
    {
        var pairs = allFiles
            .GroupBy(f => f.PairId)
            .ToDictionary(
                g => g.Key,
                g => g.ToDictionary(f => f.Language, f => f)
            );

        var statusData = new StatusFile
        {
            SchemaVersion = _statusSchemaVersion,
            Languages = config.Languages,
            Pairs = []
        };

        foreach (var (pairId, langDict) in pairs.OrderBy(p => p.Key))
        {
            var revisions = new Dictionary<string, int>();
            var files = new Dictionary<string, string>();
            var contentHashes = new Dictionary<string, string>();

            foreach (var lang in config.Languages)
            {
                if (langDict.TryGetValue(lang, out var docFile))
                {
                    revisions[lang] = docFile.Revision;
                    files[lang] = docFile.RelativePath;
                    if (!string.IsNullOrEmpty(docFile.ContentHash))
                        contentHashes[lang] = docFile.ContentHash;
                }
            }

            var status = DetermineStatus(revisions, config.Languages);

            StatusPairEntry? oldEntry = null;
            var oldEntryExists = previousStatus?.Pairs.TryGetValue(pairId, out oldEntry) == true;
            var previousRevisions = oldEntryExists && oldEntry is not null
                ? (RevisionsEqual(oldEntry.Revisions, revisions)
                    ? new Dictionary<string, int>(oldEntry.PreviousRevisions)
                    : new Dictionary<string, int>(oldEntry.Revisions))
                : [];

            statusData.Pairs[pairId] = new StatusPairEntry
            {
                Status = status,
                Revisions = revisions,
                PreviousRevisions = previousRevisions,
                Files = files,
                ContentHashes = contentHashes
            };
        }

        var json = JsonSerializer.Serialize(statusData, _jsonOptions);
        var statusPath = Path.Combine(config.DocsFullPath, ".sync-status.json");
        var oldJson = File.Exists(statusPath) ? File.ReadAllText(statusPath) : null;
        if (oldJson != json)
        {
            File.WriteAllText(statusPath, json);
            Console.WriteLine($"  GENERATED: .sync-status.json");
        }
        else
        {
            Console.WriteLine($"  SKIPPED (unchanged): .sync-status.json");
        }
    }

    private static bool RevisionsEqual(
        Dictionary<string, int> left,
        Dictionary<string, int> right)
    {
        if (left.Count != right.Count)
            return false;

        foreach (var (lang, revision) in left)
            if (!right.TryGetValue(lang, out var other) || other != revision)
                return false;

        return true;
    }

    private static StatusFile? ReadPreviousStatus(Config config)
    {
        var statusPath = Path.Combine(config.DocsFullPath, ".sync-status.json");
        if (!File.Exists(statusPath))
            return null;

        try
        {
            return JsonSerializer.Deserialize<StatusFile>(File.ReadAllText(statusPath), _jsonOptions);
        }
        catch (JsonException)
        {
            // A malformed generated snapshot is not source documentation; the
            // next generate rebuilds it and validate reports the fresh state.
            return null;
        }
    }

    private static string DetermineStatus(Dictionary<string, int> revisions, List<string> languages)
    {
        var distinctRevisions = revisions.Values.Distinct().ToList();

        if (revisions.Count < languages.Count)
        {
            var missing = languages.Where(l => !revisions.ContainsKey(l)).ToList();
            return $"missing-{string.Join(",", missing)}";
        }

        if (distinctRevisions.Count == 1)
            return "synced";

        var maxLang = revisions.OrderByDescending(kv => kv.Value).First();
        return $"{maxLang.Key}-ahead";
    }

    private sealed class RevisionPlan(
        DocFile file,
        int oldRevision,
        string? oldHash,
        bool isNew,
        List<DocContentEvent> events)
    {
        public DocFile File { get; } = file;
        public int OldRevision { get; } = oldRevision;
        public string? OldHash { get; } = oldHash;
        public bool IsNew { get; } = isNew;
        public List<DocContentEvent> Events { get; } = events;
    }

    private static int GetCommitOrder(string? commitSha, Dictionary<string, int> commitOrder)
    {
        // A null sha is the synthetic uncommitted working-tree event and must
        // always replay after every committed event.
        if (commitSha is not null && commitOrder.TryGetValue(commitSha, out var order))
            return order;

        return int.MaxValue;
    }

    private sealed record PairRevisionEvent(string? CommitSha, long Timestamp, string Language);

    private sealed class StatusFile
    {
        [JsonPropertyName("schema_version")]
        public int SchemaVersion { get; set; }

        [JsonPropertyName("languages")]
        public List<string> Languages { get; set; } = [];

        [JsonPropertyName("pairs")]
        public Dictionary<string, StatusPairEntry> Pairs { get; set; } = [];
    }

    private sealed class StatusPairEntry
    {
        [JsonPropertyName("status")]
        public string Status { get; set; } = "";

        [JsonPropertyName("revisions")]
        public Dictionary<string, int> Revisions { get; set; } = [];

        [JsonPropertyName("previous_revisions")]
        public Dictionary<string, int> PreviousRevisions { get; set; } = [];

        [JsonPropertyName("files")]
        public Dictionary<string, string> Files { get; set; } = [];

        [JsonPropertyName("content_hashes")]
        public Dictionary<string, string>? ContentHashes { get; set; }
    }
}
