<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RollForward>LatestMajor</RollForward>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <UseAppHost>true</UseAppHost>
        <NoWarn>$(NoWarn);CA1707</NoWarn>
    </PropertyGroup>

    <PropertyGroup>
        <CollectCoverage>true</CollectCoverage>
        <CoverletOutputFormat>cobertura</CoverletOutputFormat>
        <Include>[Origo.ConsoleBridge]*</Include>
        <Threshold>80</Threshold>
        <ThresholdType>line</ThresholdType>
        <ThresholdStat>total</ThresholdStat>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.msbuild">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="xunit.v3"/>
        <PackageReference Include="xunit.runner.visualstudio">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Origo.ConsoleBridge\Origo.ConsoleBridge.csproj"/>
        <ProjectReference Include="..\Origo.TestSupport\Origo.TestSupport.csproj"/>
    </ItemGroup>

</Project>
